version: "3.8"
services:
    db_yup:
        image: mysql
        container_name: db_yup
        volumes:
            - db-yup-data:/var/lib/mysql
        ports:
            - 3346:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    phpmyadmin_yup:
        image: phpmyadmin
        container_name: phpmyadmin_yup
        depends_on:
            - db_yup
        ports:
            - 8081:80
        environment:
            PMA_HOST: db_yup
    www_yup:
        build: php
        container_name: www_yup
        ports:
          - "8741:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
volumes:
  db-yup-data:
